plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-2.4.0.cjs

packageExtensions:
  react-icons@*:
    peerDependencies:
      prop-types: "*"
  react-styleguidist@*:
    peerDependencies:
      webpack: "*"